name: GitHub Pages Deploy

on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm deps
        working-directory: ./
        run: npm i
      - name: Test
        working-directory: ./
        run: npm run test

  Build-and-Deploy:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install npm deps
        working-directory: ./
        run: npm i
      - name: Build app
        working-directory: ./
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./dist


